/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create a new (untrusted) account and return a session token.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and return a fresh session token.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidate the caller's session token.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the currently authenticated user (used to validate a stored token on app launch).
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Update mutable profile fields for the currently authenticated user.
         */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/users/me/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Register Push Token
         * @description Register an Expo push token for the authenticated user.
         *
         *     Idempotent: calling again with the same token value is a no-op. If the token is already
         *     registered to a different user (e.g. after an account switch on the same device), it is
         *     re-assigned to the current user.
         */
        put: operations["register_push_token_users_me_push_token_put"];
        post?: never;
        /**
         * Deregister Push Token
         * @description Remove a specific push token for the current user (called on logout from a device).
         *
         *     No-op if the token is not found or belongs to a different user.
         */
        delete: operations["deregister_push_token_users_me_push_token_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Journeys
         * @description Return the authenticated user's saved journeys, newest first.
         */
        get: operations["list_journeys_journeys_get"];
        put?: never;
        /**
         * Save Journey
         * @description Save a journey snapshot for the authenticated user.
         */
        post: operations["save_journey_journeys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journey_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Journey
         * @description Remove a saved journey belonging to the authenticated user.
         */
        delete: operations["delete_journey_journeys__journey_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outage-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Outage Reports
         * @description Return all outage reports (newest first).
         */
        get: operations["list_outage_reports_outage_reports_get"];
        put?: never;
        /**
         * Create Outage Report
         * @description Submit a new outage report (without an image).
         *
         *     Open to anonymous callers: the report is tagged with the authenticated user's role, or
         *     `untrusted` when submitted without a valid token. To attach an image, follow up with
         *     POST /outage-reports/{id}/image.
         *
         *     When this report opens a brand-new Failure (first report for the equipment's current
         *     incident), a background task fires Expo push notifications to all authenticated users
         *     whose saved journeys pass through the affected station.
         */
        post: operations["create_outage_report_outage_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outage-reports/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Outage Reports
         * @description Live feed of outage reports via Server-Sent Events.
         *
         *     On connect, emits a `snapshot` event carrying the full currently-open feed (active reports under
         *     unresolved failures), then streams `created` / `deleted` / `resolved` events as they happen — so
         *     every (re)connection is a fresh refresh followed by live deltas. Declared before `/{report_id}`
         *     so the literal path isn't captured by the integer path param.
         */
        get: operations["stream_outage_reports_outage_reports_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outage-reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Outage Report
         * @description Return a single outage report by ID.
         */
        get: operations["get_outage_report_outage_reports__report_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Outage Report
         * @description Soft-delete an outage report (creates a deletion record, row is kept).
         */
        delete: operations["delete_outage_report_outage_reports__report_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outage-reports/{report_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Image
         * @description Download the raw image attached to an outage report.
         */
        get: operations["download_image_outage_reports__report_id__image_get"];
        put?: never;
        /**
         * Upload Image
         * @description Attach (or replace) an image for an existing outage report.
         *
         *     Accepted content types: JPEG, PNG, WebP, GIF.
         */
        post: operations["upload_image_outage_reports__report_id__image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Failures
         * @description Return all failures with computed first_reported and active report count.
         */
        get: operations["list_failures_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failures/{failure_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Failure
         * @description Return a single failure with its equipment details and active reports.
         */
        get: operations["get_failure_failures__failure_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failures/{failure_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Resolve Failure
         * @description Mark a failure as resolved. New reports for the same equipment will start a fresh failure.
         */
        patch: operations["resolve_failure_failures__failure_id__resolve_patch"];
        trace?: never;
    };
    "/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stations
         * @description Return all available stations, each with its platforms and per-platform step-free access.
         */
        get: operations["list_stations_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Equipment Types
         * @description Return all available equipment types.
         */
        get: operations["list_equipment_types_equipment_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Equipment
         * @description Return all equipment, optionally filtered by station_id.
         */
        get: operations["list_equipment_equipment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthResponse
         * @description Returned by signup and login: the session token plus the authenticated user.
         */
        AuthResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["UserPublic"];
        };
        /** Body_upload_image_outage_reports__report_id__image_post */
        Body_upload_image_outage_reports__report_id__image_post: {
            /** File */
            file: string;
        };
        /**
         * EquipmentSummary
         * @description Equipment row with its Station and EquipmentType inlined for client convenience.
         */
        EquipmentSummary: {
            /** Id */
            id: number;
            station: components["schemas"]["StationSchema"];
            equipment_type: components["schemas"]["EquipmentTypeSchema"];
            /** Connection */
            connection: string;
        };
        /**
         * EquipmentTypeSchema
         * @description Public representation of an EquipmentType row (e.g. "lift", "escalator").
         */
        EquipmentTypeSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * FailureDetail
         * @description Failure as returned by GET /failures/{id} (with active reports).
         */
        FailureDetail: {
            /** Id */
            id: number;
            equipment: components["schemas"]["EquipmentSummary"];
            /** Resolved */
            resolved: boolean;
            /** First Reported */
            first_reported: string | null;
            /** Reports */
            reports: components["schemas"]["OutageReportSummary"][];
        };
        /**
         * FailureInline
         * @description Minimal failure info embedded inside an OutageReportSummary.
         */
        FailureInline: {
            /** Id */
            id: number;
            equipment: components["schemas"]["EquipmentSummary"];
            /** Resolved */
            resolved: boolean;
        };
        /**
         * FailureSummary
         * @description Failure as returned by GET /failures (with computed aggregates).
         */
        FailureSummary: {
            /** Id */
            id: number;
            equipment: components["schemas"]["EquipmentSummary"];
            /** Resolved */
            resolved: boolean;
            /** First Reported */
            first_reported: string | null;
            /** Last Reported */
            last_reported: string | null;
            /** Report Count */
            report_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OutageReportCreate
         * @description Request body for POST /outage-reports — the image is uploaded separately.
         */
        OutageReportCreate: {
            /** Equipment Id */
            equipment_id: number;
            /**
             * Breakdown Time
             * Format: date-time
             */
            breakdown_time: string;
            /** Description */
            description?: string | null;
        };
        /**
         * OutageReportSummary
         * @description Outage report as returned to clients; `image_content_type` indicates an image is available
         *     via GET /outage-reports/{id}/image — the bytes themselves are never embedded in JSON.
         */
        OutageReportSummary: {
            /** Id */
            id: number;
            /** Failure Id */
            failure_id: number;
            failure: components["schemas"]["FailureInline"];
            /**
             * Breakdown Time
             * Format: date-time
             */
            breakdown_time: string;
            /** Description */
            description?: string | null;
            /** Image Content Type */
            image_content_type?: string | null;
            /** Reporter Role */
            reporter_role: string;
        };
        /**
         * PlatformSchema
         * @description Public representation of a Platform row, including its own step-free access.
         */
        PlatformSchema: {
            /** Name */
            name: string;
            step_free: components["schemas"]["PlatformStepFree"];
            /** Lines */
            lines: string[];
        };
        /**
         * PlatformStepFree
         * @description A single platform's step-free accessibility, as published by TfL.
         *
         *     Ordered weakest-to-strongest. `to_train` and `full` both mean a passenger can board the
         *     train without a step; TfL labels them differently in the feed so both are preserved.
         * @enum {string}
         */
        PlatformStepFree: "none" | "to_platform" | "to_train" | "full";
        /** PushTokenBody */
        PushTokenBody: {
            /** Token */
            token: string;
        };
        /**
         * SavedJourneyCreate
         * @description Request body for POST /journeys.
         */
        SavedJourneyCreate: {
            /** Id */
            id: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /** Payload */
            payload: string;
        };
        /**
         * SavedJourneyOut
         * @description A saved journey as returned to the client.
         */
        SavedJourneyOut: {
            /** Id */
            id: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /** Payload */
            payload: string;
        };
        /**
         * StationDetail
         * @description A station plus its platforms, each with their own step-free access and lines.
         *
         *     `step_free` is the summary derived from these platforms (see Station.step_free).
         */
        StationDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            step_free: components["schemas"]["StepFree"];
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Platforms */
            platforms: components["schemas"]["PlatformSchema"][];
        };
        /**
         * StationSchema
         * @description Public representation of a Station row. Kept lean because it is embedded in other
         *     payloads (e.g. equipment / outage reports); use StationDetail for the platform breakdown.
         */
        StationSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            step_free: components["schemas"]["StepFree"];
        };
        /**
         * StepFree
         * @description A station's step-free accessibility, as published by TfL.
         *
         *     Ordered weakest-to-strongest: no step-free access, step-free from street to platform
         *     only, and step-free all the way from street onto the train.
         * @enum {string}
         */
        StepFree: "none" | "to_platform" | "to_vehicle";
        /**
         * UserCreate
         * @description Request body for POST /auth/signup and POST /auth/login.
         */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * UserPublic
         * @description A user as exposed to clients — never includes the password hash.
         */
        UserPublic: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Railcard */
            railcard?: string | null;
            /** Traveller Type */
            traveller_type?: string | null;
        };
        /**
         * UserUpdate
         * @description Request body for PATCH /auth/me — all fields optional.
         */
        UserUpdate: {
            /** Railcard */
            railcard?: string | null;
            /** Traveller Type */
            traveller_type?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_push_token_users_me_push_token_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deregister_push_token_users_me_push_token_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_journeys_journeys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJourneyOut"][];
                };
            };
        };
    };
    save_journey_journeys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedJourneyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJourneyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_journey_journeys__journey_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outage_reports_outage_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"][];
                };
            };
        };
    };
    create_outage_report_outage_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutageReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_outage_reports_outage_reports_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_outage_report_outage_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_outage_report_outage_reports__report_id__delete: {
        parameters: {
            query?: {
                reason?: string | null;
            };
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_image_outage_reports__report_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_outage_reports__report_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_outage_reports__report_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_failures_failures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureSummary"][];
                };
            };
        };
    };
    get_failure_failures__failure_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                failure_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_failure_failures__failure_id__resolve_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                failure_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stations_stations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationDetail"][];
                };
            };
        };
    };
    list_equipment_types_equipment_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentTypeSchema"][];
                };
            };
        };
    };
    list_equipment_equipment_get: {
        parameters: {
            query?: {
                station_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
