/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/outage-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Outage Reports
         * @description Return all outage reports (newest first).
         */
        get: operations["list_outage_reports_outage_reports_get"];
        put?: never;
        /**
         * Create Outage Report
         * @description Submit a new outage report (without an image).
         *
         *     To attach an image, follow up with POST /outage-reports/{id}/image.
         */
        post: operations["create_outage_report_outage_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outage-reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Outage Report
         * @description Return a single outage report by ID.
         */
        get: operations["get_outage_report_outage_reports__report_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Outage Report
         * @description Soft-delete an outage report (creates a deletion record, row is kept).
         */
        delete: operations["delete_outage_report_outage_reports__report_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outage-reports/{report_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Image
         * @description Download the raw image attached to an outage report.
         */
        get: operations["download_image_outage_reports__report_id__image_get"];
        put?: never;
        /**
         * Upload Image
         * @description Attach (or replace) an image for an existing outage report.
         *
         *     Accepted content types: JPEG, PNG, WebP, GIF.
         */
        post: operations["upload_image_outage_reports__report_id__image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Failures
         * @description Return all failures with computed first_reported and active report count.
         */
        get: operations["list_failures_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failures/{failure_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Failure
         * @description Return a single failure with its equipment details and active reports.
         */
        get: operations["get_failure_failures__failure_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failures/{failure_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Resolve Failure
         * @description Mark a failure as resolved. New reports for the same equipment will start a fresh failure.
         */
        patch: operations["resolve_failure_failures__failure_id__resolve_patch"];
        trace?: never;
    };
    "/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stations
         * @description Return all available stations.
         */
        get: operations["list_stations_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Equipment Types
         * @description Return all available equipment types.
         */
        get: operations["list_equipment_types_equipment_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Equipment
         * @description Return all equipment, optionally filtered by station_id.
         */
        get: operations["list_equipment_equipment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_image_outage_reports__report_id__image_post */
        Body_upload_image_outage_reports__report_id__image_post: {
            /** File */
            file: string;
        };
        /**
         * EquipmentSummary
         * @description Equipment row with its Station and EquipmentType inlined for client convenience.
         */
        EquipmentSummary: {
            /** Id */
            id: number;
            station: components["schemas"]["StationSchema"];
            equipment_type: components["schemas"]["EquipmentTypeSchema"];
            /** Connection */
            connection: string;
        };
        /**
         * EquipmentTypeSchema
         * @description Public representation of an EquipmentType row (e.g. "lift", "escalator").
         */
        EquipmentTypeSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * FailureDetail
         * @description Failure as returned by GET /failures/{id} (with active reports).
         */
        FailureDetail: {
            /** Id */
            id: number;
            equipment: components["schemas"]["EquipmentSummary"];
            /** Resolved */
            resolved: boolean;
            /** First Reported */
            first_reported: string | null;
            /** Reports */
            reports: components["schemas"]["OutageReportSummary"][];
        };
        /**
         * FailureInline
         * @description Minimal failure info embedded inside an OutageReportSummary.
         */
        FailureInline: {
            /** Id */
            id: number;
            equipment: components["schemas"]["EquipmentSummary"];
            /** Resolved */
            resolved: boolean;
        };
        /**
         * FailureSummary
         * @description Failure as returned by GET /failures (with computed aggregates).
         */
        FailureSummary: {
            /** Id */
            id: number;
            equipment: components["schemas"]["EquipmentSummary"];
            /** Resolved */
            resolved: boolean;
            /** First Reported */
            first_reported: string | null;
            /** Last Reported */
            last_reported: string | null;
            /** Report Count */
            report_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OutageReportCreate
         * @description Request body for POST /outage-reports — the image is uploaded separately.
         */
        OutageReportCreate: {
            /** Equipment Id */
            equipment_id: number;
            /**
             * Breakdown Time
             * Format: date-time
             */
            breakdown_time: string;
            /** Description */
            description?: string | null;
        };
        /**
         * OutageReportSummary
         * @description Outage report as returned to clients; `image_content_type` indicates an image is available
         *     via GET /outage-reports/{id}/image — the bytes themselves are never embedded in JSON.
         */
        OutageReportSummary: {
            /** Id */
            id: number;
            /** Failure Id */
            failure_id: number;
            failure: components["schemas"]["FailureInline"];
            /**
             * Breakdown Time
             * Format: date-time
             */
            breakdown_time: string;
            /** Description */
            description?: string | null;
            /** Image Content Type */
            image_content_type?: string | null;
        };
        /**
         * StationSchema
         * @description Public representation of a Station row.
         */
        StationSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            step_free: components["schemas"]["StepFree"];
        };
        /**
         * StepFree
         * @description A station's step-free accessibility, as published by TfL.
         *
         *     Ordered weakest-to-strongest: no step-free access, step-free from street to platform
         *     only, and step-free all the way from street onto the train.
         * @enum {string}
         */
        StepFree: "none" | "to_platform" | "to_vehicle";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_outage_reports_outage_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"][];
                };
            };
        };
    };
    create_outage_report_outage_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutageReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outage_report_outage_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_outage_report_outage_reports__report_id__delete: {
        parameters: {
            query?: {
                reason?: string | null;
            };
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_image_outage_reports__report_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_outage_reports__report_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_outage_reports__report_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_failures_failures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureSummary"][];
                };
            };
        };
    };
    get_failure_failures__failure_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                failure_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_failure_failures__failure_id__resolve_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                failure_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stations_stations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationSchema"][];
                };
            };
        };
    };
    list_equipment_types_equipment_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentTypeSchema"][];
                };
            };
        };
    };
    list_equipment_equipment_get: {
        parameters: {
            query?: {
                station_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
