import json
from pathlib import Path

from sqlalchemy.orm import Session

from app.models.equipment import Equipment
from app.models.equipment_type import EquipmentType
from app.models.line import Line
from app.models.platform import Platform
from app.models.station import StepFree, Station

# Reference data inserted on every startup. Idempotent (skips rows that already exist),
# so editing the dataset adds new entries to existing databases but never removes or renames.
#
# The station / platform / facility data lives in data/stations.json, generated by
# scripts/generate_lift_seed.py from TfL's published step-free access feed — re-run that
# script to refresh it. Each entry is { name, step_free, escalators, platforms: [{ name,
# lines }], ... }. Lifts come from one of two sources, in priority order:
#   - lift_units: a list of real lifts { name, connection } from the feed (preferred); or
#   - lifts: an integer count, used to synthesise placeholder units for stations the feed
#     does not list individual lifts for.

_DATA_PATH = Path(__file__).resolve().parent / "data" / "stations.json"
_EQUIPMENT_TYPES = ["lift", "escalator"]


def _load_station_data() -> list[dict]:
    return json.loads(_DATA_PATH.read_text(encoding="utf-8"))


def seed_defaults(db: Session) -> None:
    """Insert default equipment types, stations, platforms, and equipment if not already present."""
    stations_data = _load_station_data()

    # Equipment types --------------------------------------------------------
    types = {t.name: t for t in db.query(EquipmentType).all()}
    for name in _EQUIPMENT_TYPES:
        if name not in types:
            types[name] = EquipmentType(name=name)
            db.add(types[name])
    db.flush()

    # Stations ---------------------------------------------------------------
    stations = {s.name: s for s in db.query(Station).all()}
    for data in stations_data:
        if data["name"] not in stations:
            stations[data["name"]] = Station(
                name=data["name"], step_free=StepFree(data.get("step_free", "none"))
            )
            db.add(stations[data["name"]])
    db.flush()

    # Lines (canonical, one row per distinct name) ---------------------------
    lines = {line.name: line for line in db.query(Line).all()}

    def lines_for(raw: str) -> list[Line]:
        """Resolve a comma-separated line string into shared Line rows, creating any missing."""
        result = []
        for name in (part.strip() for part in raw.split(",")):
            if not name:
                continue
            if name not in lines:
                lines[name] = Line(name=name)
                db.add(lines[name])
            result.append(lines[name])
        return result

    # Platforms (unique per station + name) ----------------------------------
    platforms = {(p.station_id, p.name): p for p in db.query(Platform).all()}
    for data in stations_data:
        station = stations[data["name"]]
        for plat in data["platforms"]:
            key = (station.id, plat["name"])
            if key not in platforms:
                platforms[key] = Platform(
                    station_id=station.id,
                    name=plat["name"],
                    lines=lines_for(plat.get("lines", "")),
                )
                db.add(platforms[key])
    db.flush()

    # Equipment. The (station, type, connection) key keeps inserts idempotent.
    existing = {
        (e.station_id, e.equipment_type_id, e.connection) for e in db.query(Equipment).all()
    }

    def add_equipment(station_id: int, type_id: int, connection: str, platform_id: int | None) -> None:
        key = (station_id, type_id, connection)
        if key in existing:
            return
        existing.add(key)
        db.add(Equipment(
            station_id=station_id,
            equipment_type_id=type_id,
            platform_id=platform_id,
            connection=connection,
        ))

    lift_type_id = types["lift"].id
    escalator_type_id = types["escalator"].id
    for data in stations_data:
        station = stations[data["name"]]
        station_platforms = [platforms[(station.id, p["name"])] for p in data["platforms"]]

        # Lifts: prefer the feed's real, named units; otherwise synthesise from the count.
        lift_units = data.get("lift_units")
        if lift_units:
            for unit in lift_units:
                add_equipment(
                    station.id, lift_type_id, f"{unit['name']}: {unit['connection']}", None
                )
        else:
            for i in range(data.get("lifts", 0)):
                platform = station_platforms[i % len(station_platforms)] if station_platforms else None
                target = platform.name if platform else "platforms"
                add_equipment(
                    station.id, lift_type_id, f"Lift {i + 1}: street → {target}",
                    platform.id if platform else None,
                )

        # Escalators: count-based, distributed round-robin across the station's platforms.
        for i in range(data.get("escalators", 0)):
            platform = station_platforms[i % len(station_platforms)] if station_platforms else None
            target = platform.name if platform else "platforms"
            add_equipment(
                station.id, escalator_type_id, f"Escalator {i + 1}: street → {target}",
                platform.id if platform else None,
            )
    db.commit()
